function sys = mylinearize(io,op)
% MYLINEARIZE Linearize the Simulink model - mod3.
%
% SYS = MYLINEARIZE(IO,OP) linearizes the Simulink model mod3
% using the analysis I/Os IO about the operating point OP.

% MATLAB(R) file generated by MATLAB(R) 9.2 and Simulink Control Design (TM) 4.5.
%
% Generated on: 26-Feb-2019 02:37:55

%% Specify the model name
model = 'mod3';

%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
step(sys)
margin(sys)
