%% Exact linearization of the Simulink model mod3
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.2 and Simulink Control Design (TM) 4.5.
%
% Generated on: 01-Mar-2019 11:10:18

%% Specify the model name
model = 'mod1';

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(model);

%% Specify the operating point
% Use the model initial condition
op = operpoint(model);


%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
step(sys)
margin(sys)
